---
title: "Behavioral Data Preprocessing"
author: "Ari Dyckovsky"
---

```{r, setup, include=FALSE}
# Knitr options
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  strip.white = TRUE,
  highlight = TRUE
)

# Load packages
library(tidyverse)
library(targets)
library(here)
library(withr)

# R options
options(
  width = 90
)
```

Construct a list of the extracted behavioral CSV file targets by participant.

```{r}
extracted_behavioral_csv_files <- participants %>%
  unlist(use.names = FALSE) %>%
  map(~ str_c("extracted_behavioral_csv_file_", .x))
```

Read CSVs into dataframe `combined_df` after using `tar_read_raw` to get the file path for participants from targets. Will include _all_ participants and include an `id` column to identify the participant individually.

```{r, get-combined-data}
withr::with_dir(here::here(), {
  combined_df <- extracted_behavioral_csv_files %>%
    map_df(~ read_csv(tar_read_raw(.)))
})

# Transform step and response types to 0 or 1 integer values to simulate boolean behavior.
combined_df <- combined_df %>%
  mutate(
    is_signal = as.integer(step_type > 1),
    is_response = as.integer(resp_type)
  )
```

Count of participants by unique id.

```{r}
length(unique(combined_df$id))
```

```{r}
combined_df %>%
  select(trial, id, is_response, is_signal, resp_time, step_time) %>%
  group_by(id) %>%
  tally(is_response) %>%
  summarise(mean(n), sd(n), min(n), max(n))
```


```{r}
HIT_INTERVAL <- 8

combined_df %>%
  select(trial, id, is_response, is_signal, resp_time, step_time) %>%
  filter(is_signal > 0) %>%
  select(id, trial, step_time) %>%
  mutate(
    response_window_min = step_time,
    response_window_max = step_time + HIT_INTERVAL
  ) %>%
  select(-step_time)
```

```{r}
combined_df %>%
  select(trial, id, is_response, is_signal, resp_time, step_time) %>%
  filter(is_response > 0) %>%
  select(id, trial, resp_time) 
```
