---
title: "Summary Notebook: Incompletes"
author: "Ari Dyckovsky"
---

```{r, notebook-options, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  strip.white = TRUE,
  highlight = TRUE,
  warning = FALSE,
  message = FALSE
)
```

## Participants who did not complete the task

### How many participants were incomplete?

A total of **7 participants** of 57 recruited did _not complete_ the task.

### What were the reasons participants did not complete the task?

The reasons participants did not complete the task are briefly described
in the following list by participant identifier:

- CSN003 had calibration issues (wore glasses)
- CSN014 had calibration issues (too much eye makeup)
- CSN024 stopped early due to illness
- CSN028 had calibration issues (difficult eye shape)
- CSN031 had calibration issues (wore glasses)
- CSN046 stopped early due to graphic images
- CSN050 had calibration issues (wore contacts)

### Can we group the incompletes by common reasons?

Yes, the incompletes can be grouped by two common reasons:

1. Calibration difficulty (i.e., corrective lenses or make-up) applies to 5 of 7 incompletes
2. Deciding to stop the task early (i.e., illness or difficulty with image content) applies to 2 of 7 incompletes
